export const sendInvoiceByEmailHTML = ({
  name,
  month,
}: {
  name: string;
  month?: string;
}): string => {
  return `
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Invoice</title>
      <style>
        body { margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f9f9f9; }
        .container { width: 100%; max-width: 600px; margin: 0 auto; padding: 20px; }
        .card { background-color: #fff; border-radius: 8px; padding: 30px; box-shadow: 0 0 10px rgba(0,0,0,0.05); }
        .logo img { max-width: 200px; margin-bottom: 20px; }
        h2 { color: #333; margin: 0 0 20px 0; }
        p { color: #555; line-height: 1.5; }
        a.button { display: inline-block; background-color: #007bff; color: #fff; text-decoration: none; padding: 10px 20px; border-radius: 4px; font-weight: bold; }
        .footer { font-size: 12px; color: #999; padding-top: 20px; text-align: center; }
        @media only screen and (max-width: 600px) {
          .card { padding: 20px; }
          .logo img { max-width: 150px; }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="card">
          <div class="logo" style="text-align:center;">
            <img src="https://i.ibb.co.com/HfrxM4Xf/Business-Food-Service.png" alt="Business Food Service Logo"/>
          </div>
          <h2>📄 Monthly Invoice</h2>
          <p>Hi <b>${name}</b>,</p>
          <p>Please find attached your invoice for <b>${month || "this month"}</b>. Thank you for using our service!</p>
          <p>If you have any questions, feel free to reach out to our support team.</p>
          <p style="text-align:center; padding: 20px 0;">
            <a href="#" class="button">View Dashboard</a>
          </p>
          <div class="footer">
            <p>Generated by Business Food Service</p>
            <p>© ${new Date().getFullYear()} All rights reserved</p>
          </div>
        </div>
      </div>
    </body>
  </html>
  `;
};
